[package]
name = "pqrs"
version = "0.1.2"
authors = ["Manoj Karthick"]
description = "Apache Parquet command-line tools and utilities"
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://github.com/manojkarthick/pqrs"
repository = "https://github.com/manojkarthick/pqrs"
keywords = ["cli", "arrow", "parquet"]
categories = ["command-line-utilities"]

[dependencies]
thiserror = "1.0.22"
log = "0.4.11"
env_logger = "0.8.2"
parquet = { rev = "6698eed", features = ["cli", "arrow"], git = "https://github.com/apache/arrow-rs.git" }
arrow = { rev = "6698eed", git = "https://github.com/apache/arrow-rs.git" }
clap = "2.33.3"
rand = "0.8.3"

[dev-dependencies]
tempfile = "3.2.0"
assert_cmd = "1.0.3"
predicates = "1.0.7"
